
import { useState } from 'react'
import { api, errorMessage } from '../../api/client'
import { useToast } from '../../components/Toast'
import { Card, StatCard } from '../../components/ui'
import { datetime, inr } from '../../lib/format'

export default function ReportsPage() {
  const toast = useToast()
  const [report, setReport] = useState(null)
  const [busy, setBusy] = useState(false)

  async function generate() {
    setBusy(true)
    try {
      const { data } = await api.post('/compliance/reports/generate')
      setReport(data)
    } catch (e) { toast.error(errorMessage(e)) } finally { setBusy(false) }
  }

  function exportCsv() {
    if (!report) return
    const rows = [
      ['FundMatrix Compliance Report'],
      ['Generated At', report.generatedAt],
      ['Generated By', report.generatedBy],
      [],
      ['KYC Status', 'Count'],
      ['Compliant', report.kyc.compliant],
      ['Pending', report.kyc.pending],
      ['Non-Compliant', report.kyc.nonCompliant],
      ['Expired', report.kyc.expired],
      ['Total', report.kyc.total],
      [],
      ['Transaction Flags', 'Count'],
      ['Open', report.flagsOpen],
      ['Reviewed', report.flagsReviewed],
      ['Escalated', report.flagsEscalated],
      ['Cleared', report.flagsCleared],
      ['Total Flagged', report.flaggedTotalCount],
      ['Total Flagged Amount (INR)', report.flaggedTotalAmount],
    ]
    const csv = rows.map((r) => r.map((c) => `"${c ?? ''}"`).join(',')).join('\n')
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = `compliance-report-${(report.generatedAt || '').slice(0, 10)}.csv`
    a.click()
    URL.revokeObjectURL(a.href)
  }

  return (
    <>
      <div className="page-head d-flex justify-content-between align-items-center flex-wrap gap-3">
        <div>
          <h1>Regulatory Return Preparation</h1>
          <p>Generate a compliance summary and export it for regulatory filing</p>
        </div>
        <button className="btn btn-primary" disabled={busy} onClick={generate}>{busy ? 'Generating…' : 'Generate Report'}</button>
      </div>

      {!report ? (
        <Card><div className="empty">Click “Generate Report” to prepare the current compliance return.</div></Card>
      ) : (
        <div id="report-print">
          <Card title="Compliance Report"
            hint={`Generated ${datetime(report.generatedAt)} by ${report.generatedBy}`}
            action={
              <div className="d-flex flex-wrap gap-2">
                <button className="btn btn-ghost btn-sm" onClick={exportCsv}>Export CSV</button>
                <button className="btn btn-ghost btn-sm" onClick={() => window.print()}>Print / PDF</button>
              </div>
            }>
            <h3 style={{ margin: '4px 0 10px' }}>KYC Compliance</h3>
            <div className="grid cols-4">
              <StatCard label="Compliant" value={report.kyc.compliant} icon="✓" />
              <StatCard label="Pending" value={report.kyc.pending} icon="◷" />
              <StatCard label="Non-Compliant" value={report.kyc.nonCompliant} icon="⚠" />
              <StatCard label="Expired" value={report.kyc.expired} icon="⊗" />
            </div>

            <h3 style={{ margin: '18px 0 10px' }}>Transaction Flags</h3>
            <div className="grid cols-4">
              <StatCard label="Open" value={report.flagsOpen} icon="⚑" />
              <StatCard label="Reviewed" value={report.flagsReviewed} icon="◈" />
              <StatCard label="Escalated" value={report.flagsEscalated} icon="↑" />
              <StatCard label="Cleared" value={report.flagsCleared} icon="✓" />
            </div>
            <div className="kv" style={{ marginTop: 14 }}>
              <span className="k">Total flagged transactions</span><span className="v">{report.flaggedTotalCount}</span>
            </div>
            <div className="kv">
              <span className="k">Total flagged value</span><span className="v">{inr(report.flaggedTotalAmount)}</span>
            </div>
          </Card>
        </div>
      )}
    </>
  )
}
